### ISSUE TITLE
Ackchyually

### ISSUE THREAD

**Issue by abdelhai** [dukebody/meetup-aggregator#1]
Hey!

Mustafa from Deta here, saw the following in your readme:  

> Esto no es escalable ni ACID ni nada y probablemente sea mejor usar una base de datos de verdad. :D

Although you are correct stating that Base is not ACID compliant, I just wanted to clarify that it is in fact a real (non-relational) database that is infinitely scalable with great performance (depending on region availability).

Want to also thank you for giving Deta a try! Cheers 😊

**Comment by dukebody** [comment]
You are right! I will modify the README. Thanks for taking the time to look for projects using Deta and comment on them :)

**Comment by dukebody** [comment]
Fixed! :)

**Comment by abdelhai** [comment]
Awesome! 🎉
